language: cpp

sudo: required
compiler: clang
os: osx

cache:
  directories:
    - ~/Qt/

script:
  - if [ ! -e ~/Qt/5.10.1/ ] ; then
      wget https://download.qt.io/official_releases/qt/5.10/5.10.1/qt-opensource-mac-x64-5.10.1.dmg;
      sudo hdiutil attach -noverify ./qt-opensource-mac-x64-5.10.1.dmg;
      /Volumes/qt-opensource-mac-x64-5.10.1/qt-opensource-mac-x64-5.10.1.app/Contents/MacOS/qt-opensource-mac-x64-5.10.1 --platform minimal --script qt_script_osx.qs;
    fi
  - cd DNAI
  - git submodule init
  - git submodule update
  - ~/Qt/5.10.1/clang_64/bin/qmake DNAI.pro
  - make
  - cd ../Server
  - ~/Qt/5.10.1/clang_64/bin/qmake Server.pro
  - make
