language: cpp

os: osx

osx_image: xcode9.2

compiler: clang

cache:
  directories:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        ~/Qt5.9.4;
      fi

before_install:
  # repo for Qt
  brew update ;
  

script:
  - brew upgrade cmake
  - wget http://download.qt.io/official_releases/qt/5.9/5.9.4/qt-opensource-mac-x64-5.9.4.dmg
  - sudo hdiutil attach -noverify ./qt-opensource-mac-x64-5.9.4.dmg 
  - /Volumes/qt-opensource-mac-x64-5.9.4/qt-opensource-mac-x64-5.9.4.app/Contents/MacOS/qt-opensource-mac-x64-5.9.4 --platform minimal --script qt_script_osx.qs
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_PREFIX_PATH=~/Qt5.9.4/5.9/clang_64/lib/cmake
  - make all 
