language: cpp
os: linux
compiler: gcc
sudo: required
dist: trusty


cache:

  directories:

    - /opt/qt59

addons:
  apt:
    packages:
      - cmake

before_install:
  # repo for Qt
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository --yes ppa:beineri/opt-qt592-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - if [ ! -e /opt/qt59 ] ; then
      sudo apt-get --yes install qt59base qt59imageformats qt59svg qt59declarative qt59graphicaleffects qt59quickcontrols2 ;
    fi
  

before_script:
  # Qt variables
  - QTDIR="/opt/qt59"
  - PATH="$QTDIR/bin:$PATH"
  - source /opt/qt59/bin/qt59-env.sh

script:
    - g++ -v
    - export CMAKE_PREFIX_PATH=/opt/qt59/lib/cmake  ;
      cd .. ;
      bash -e ./Duly-GUI/scripts/build.sh -both
