sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

cache:
    timeout: 1000
    directories:
        - Qt

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
        packages:
            - git
            - make
            - autoconf
            - automake
            - libtool
            - cmake
            - pkg-config
            - libxml2-dev
            - libxslt1-dev
            - libzip-dev
            - libsqlite3-dev
            - libusb-1.0-0-dev
            - libssl-dev
            - libssh2-1-dev
            - libcurl4-openssl-dev
            # Not a duly-gui dependency, but a Qt dependency
            - mesa-common-dev

before_install:
    - sudo apt-get update -qq
    - if [ ! -e Qt/5.10.0 ] ; then
          rm -rf Qt ;
          wget http://download.qt.io/official_releases/qt/5.10/5.10.0/qt-opensource-linux-x64-5.10.0.run ;
          chmod +x ./qt-opensource-linux-x64-5.10.0.run ;
          ./qt-opensource-linux-x64-5.10.0.run --platform minimal --script qt-installer-noninteractive.qs --no-force-installations ;
      fi


script:
    - export CMAKE_PREFIX_PATH=$PWD/Qt/5.10.0/gcc_64/lib/cmake ;
      cd .. ;
      bash -e ./Duly-GUI/scripts/build.sh -both
