language: c++

dist: trusty

cache:
    timeout: 1000
    directories:
        - Qt
        
compiler:
  - gcc
  - clang
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-6
    - clang-3.8

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
        packages:
            - git
            - g++-6
            - clang-3.8
            - make
            - autoconf
            - automake
            - libtool
            - cmake
            - pkg-config
            - libxml2-dev
            - libxslt1-dev
            - libzip-dev
            - libsqlite3-dev
            - libusb-1.0-0-dev
            - libssl-dev
            - libssh2-1-dev
            - libcurl4-openssl-dev
            # Not a duly-gui dependency, but a Qt dependency
            - mesa-common-dev

before_install:
    - if [ ! -e Qt/5.9.1 ] ; then
          rm -rf Qt ;
          wget http://download.qt.io/official_releases/qt/5.9/5.9.1/qt-opensource-linux-x64-5.9.1.run ;
          chmod +x ./qt-opensource-linux-x64-5.9.1.run ;
          ./qt-opensource-linux-x64-5.9.1.run --platform minimal --script qt-installer-noninteractive.qs --no-force-installations ;
      fi

install:
    - "[ $CXX = g++ ] && export CXX=g++-6 || true"
    - "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"



script:
    - export CMAKE_PREFIX_PATH=$PWD/Qt/5.9.1/gcc_64/lib/cmake ;
      cd .. ;
      bash -e ./Duly-GUI/scripts/build.sh -both
