language: cpp

sudo: required
compiler: clang
os: osx

cache:
  directories:
    - ~/Qt/
    
before_script:
  - export QTDIR=~/Qt/5.10.1/clang_64
  - export PATH=$QTDIR/bin:$PATH

script:
  - if [ ! -e ~/Qt/5.10.1/ ] ; then
      wget https://download.qt.io/official_releases/qt/5.10/5.10.1/qt-opensource-mac-x64-5.10.1.dmg;
      sudo hdiutil attach -noverify ./qt-opensource-mac-x64-5.10.1.dmg;
      /Volumes/qt-opensource-mac-x64-5.10.1/qt-opensource-mac-x64-5.10.1.app/Contents/MacOS/qt-opensource-mac-x64-5.10.1 --platform minimal --script qt_script_osx.qs;
    fi
  - git submodule update --init --recursive
  - if [ -z "$TRAVIS_TAG" ]; then
      cd Gui;
      qmake DNAI.pro;
      make -j 8;
      cd ../Server;
      qmake Server.pro;
      make -j 8;
   else
      cd ./scripts/mac;
      ./install.sh --compile=true --release="$TRAVIS_TAG";
    fi
