language: cpp

sudo: required
compiler: clang
os: osx

 cache:
    directories:
     - ~/Qt/

script:
  - brew update
  - brew upgrade cmake
  - if [ ! -e ~/Qt/ ] ; then
      wget http://download.qt.io/official_releases/qt/5.9/5.9.4/qt-opensource-mac-x64-5.9.4.dmg;
      sudo hdiutil attach -noverify ./qt-opensource-mac-x64-5.9.4.dmg;
      /Volumes/qt-opensource-mac-x64-5.9.4/qt-opensource-mac-x64-5.9.4.app/Contents/MacOS/qt-opensource-mac-x64-5.9.4 --platform minimal --script qt_script_osx.qs;
	fi
  - cd DNAI
  - ~/Qt/5.9.4/clang_64/bin/qmake DNAI.pro
  - make
  - cd ../Server
  - ~/Qt/5.9.4/clang_64/bin/qmake Server.pro
  - make
