language: cpp
os: 
  - linux
  - osx
compiler: 
  - gcc
  - clang
  
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.2

cache:
  directories:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /opt/qt59 ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then Qt/5.9.4 ; fi

addons:
  apt:
    packages:
      - cmake

before_install:
  # repo for Qt
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-add-repository --yes ppa:beineri/opt-qt594-trusty ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq g++-6 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [ ! -e /opt/qt59/bin ]; then
      sudo apt-get --yes install qt59base qt59imageformats qt59svg qt59declarative qt59graphicaleffects qt59quickcontrols2 ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [ ! -e Qt/5.9.4 ]; then
      rm -rf Qt ;
      wget https://download.qt.io/official_releases/qt/5.9/5.9.4/qt-opensource-mac-x64-5.9.4.dmg ;
      chmod +x ./qt-opensource-mac-x64-5.9.4.dmg ;
      ./qt-opensource-mac-x64-5.9.4.dmg --platform minimal --script qt-installer-noninteractive.qs --no-force-installations ;
  fi
  

before_script:
  # Qt variables
  - QTDIR="/opt/qt59"
  - PATH="$QTDIR/bin:$PATH"
  - source /opt/qt59/bin/qt59-env.sh

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then g++ -v ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CMAKE_PREFIX_PATH=/opt/qt59/lib/cmake ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CMAKE_PREFIX_PATH=$PWD/Qt/5.9.4/clang/lib/cmake ; fi
      cd .. ;
      bash -e ./Duly-GUI/scripts/build.sh -both
