language: cpp
os: linux
compiler: gcc
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - cmake
      - g++-5


before_install:
  # repo for Qt
  - sudo apt-add-repository --yes ppa:beineri/opt-qt592-trusty
  - sudo apt-get -qq update

install:
  - sudo apt-get --yes install qt59base qt59imageformats qt59svg
  - export CXX="g++-5"
  - export CC="gcc-5"

before_script:
  # Qt variables
  - QTDIR="/opt/qt59"
  - PATH="$QTDIR/bin:$PATH"
  - source /opt/qt59/bin/qt59-env.sh

script:
    - g++ -v
    - export CMAKE_PREFIX_PATH=/opt/qt59/lib/cmake  ;
      cd .. ;
      bash -e ./Duly-GUI/scripts/build.sh -both
