language: cpp

os: osx

osx_image: xcode9.2

compiler: clang

cache:
  directories:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        Qt/5.9.4 ;
      fi

addons:
  apt:
    packages:
      - cmake

before_install:
  # repo for Qt
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update ;
    fi
  

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [ ! -e Qt/5.9.4 ]; then
      defaults write com.apple.frameworks.diskimages skip-verify YES;
      pwd;
      wget https://download.qt.io/official_releases/qt/5.9/5.9.4/qt-opensource-mac-x64-5.9.4.dmg ;
      hdiutil mount -noverify ./qt-opensource-mac-x64-5.9.4.dmg ;
      /Volumes/qt-opensource-mac-x64-5.9.4/qt-opensource-mac-x64-5.9.4.app --platform minimal --script qt-installer-noninteractive.qs --no-force-installations ;
    fi
  

before_script:
  # Qt variables
  - QTDIR="/opt/qt59"
  - PATH="$QTDIR/bin:$PATH"
  - source /opt/qt59/bin/qt59-env.sh

script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        export CMAKE_PREFIX_PATH=$PWD/Qt/5.9.4/clang/lib/cmake ;
      fi
    - cd .. ;
    - bash -e ./Duly-GUI/scripts/build.sh -both
