image: Visual Studio 2017

configuration:
  - release
  
artifacts:
  - path: %APPVEYOR_BUILD_FOLDER%\Dnai
    name: Dnai

install:
  - set QTDIR=C:\Qt\5.11.0\msvc2017_64
  - set PATH=%QTDIR%\bin;%PATH%
  - set PATH=C:\Qt\Tools\QtCreator\bin;%PATH%

before_build:
 - cd %APPVEYOR_BUILD_FOLDER%
 - git submodule update --init --recursive
 - call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
 - mkdir %APPVEYOR_BUILD_FOLDER%-build
 - cd %APPVEYOR_BUILD_FOLDER%-build
 - qmake -o %APPVEYOR_BUILD_FOLDER%-build -r -Wall -spec win32-msvc CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%/Gui && jom qmake_all

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - jom
  - jom install
  - windeployqt.exe "./app/release/DNAI.exe" -qmldir=%APPVEYOR_BUILD_FOLDER%\Gui\app\resources -verbose=2
  - dir /b "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC" | %APPVEYOR_BUILD_FOLDER%\scripts\tail.exe -1 > mredist.txt
  - set /p MREDIST=<mredist.txt
  - copy "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\%MREDIST%\x64\Microsoft.VC141.CRT\*" "./app/release/"
  - copy "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\%MREDIST%\x64\Microsoft.VC141.CXXAMP\*" "./app/release/"
  - copy "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\%MREDIST%\x64\Microsoft.VC141.OpenMP\*" "./app/release/"
  - mkdir %APPVEYOR_BUILD_FOLDER%\Dnai
  - RENAME "app/release" Dnai-Editor_%APPVEYOR_BUILD_VERSION%
  - move "app/Dnai-Editor_%APPVEYOR_BUILD_VERSION%" %APPVEYOR_BUILD_FOLDER%\Dnai
  - cd %APPVEYOR_BUILD_FOLDER%\Dnai
  - mkdir %APPVEYOR_BUILD_FOLDER%-server
  - cd %APPVEYOR_BUILD_FOLDER%-server
  - qmake.exe -o %APPVEYOR_BUILD_FOLDER%-server -r -Wall -spec win32-msvc CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%/Server && jom qmake_all
  - jom
  - move "release\Server.exe" %APPVEYOR_BUILD_FOLDER%\Dnai
  - cd %APPVEYOR_BUILD_FOLDER%\Dnai
  - md DNAI_UPDATER
