image: Visual Studio 2017

install:
  - set QTDIR=C:\Qt\5.11.0\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin

before_build:
- cmd: |-
    cd C:\projects\dnai-editor\Gui
    mkdir build
    qmake -r -Wall -Wlogic -Wparser ..

build:
  cd C:\projects\dnai-editor\Gui
  nmake.exe
