image: Visual Studio 2017

install:
  - set QTDIR=C:\Qt\5.11.0\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin

before_build:
- cmd: |-
    cd C:\projects\Dnai.Editor\Gui
    mkdir build
    cd build
    cmake --version
    cmake .. -G "Visual Studio 15 2017 Win64"

build:
  project: C:\projects\Dnai.Editor\Gui\build\DNAI.sln
  verbosity: minimal
  parallel: true
