image: Visual Studio 2017

configuration:
 - release

install: 
# INSTALL QT
  - set QTDIR=C:\Qt\5.11\msvc2017_64
  - set PATH=%QTDIR%\bin;%PATH%
  - set PATH=C:\Qt\Tools\QtCreator\bin;%PATH%
# INSTALL WINDOWS UTILS
  - set PATH="%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;%PATH%"
  - set PATH="%ProgramFiles(x86)%\Windows Kits\10\bin\x64\;%PATH%"
# INSTALL JQ
  - if %APPVEYOR_REPO_TAG% equ true if %APPVEYOR_REPO_BRANCH% == master install_jq
# INSTALL TAIL
  - if %APPVEYOR_REPO_TAG% equ true if %APPVEYOR_REPO_BRANCH% == master set PATH=%APPVEYOR_BUILD_FOLDER%\scripts;%PATH%
# INSTALL ENV
  - set PACKAGE_NAME=Dnai-Editor_%APPVEYOR_BUILD_VERSION%
  - set INSTALL_FOLDER=%APPVEYOR_BUILD_FOLDER%\Dnai\Editor\%APPVEYOR_BUILD_VERSION%
  - call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
  - set PATH=%APPVEYOR_BUILD_FOLDER%\scripts\windows;%PATH%

artifacts:
 - path: Windows_x64
   name: Windows_x64_Dnai-Editor_%APPVEYOR_BUILD_VERSION%
  
 - path: Core
   name: Windows_x64_Core

before_build:
# CHECKOUT
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - if %APPVEYOR_REPO_TAG% equ true if %APPVEYOR_REPO_BRANCH% == master git clone https://github.com/Gouet/Software-updater.git
  - if %APPVEYOR_REPO_TAG% equ true if %APPVEYOR_REPO_BRANCH% == master git clone https://%AppVeyorToken%@duly-eip.visualstudio.com/_git/Duly

build_script:
# BUILD EDITOR
  - build_editor
# INSTALL EDITOR
  - if %APPVEYOR_REPO_TAG% equ true if %APPVEYOR_REPO_BRANCH% == master install_editor
# BUILD SERVER
  - build_server
# INSTALL SERVER
  - if %APPVEYOR_REPO_TAG% equ true if %APPVEYOR_REPO_BRANCH% == master install_server
# BUILD UPDATER
  - if %APPVEYOR_REPO_TAG% equ true if %APPVEYOR_REPO_BRANCH% == master build_updater
# INSTALL UPDATER
  - if %APPVEYOR_REPO_TAG% equ true if %APPVEYOR_REPO_BRANCH% == master install_updater
# BUILD CORE
  - if %APPVEYOR_REPO_TAG% equ true if %APPVEYOR_REPO_BRANCH% == master build_core
# INSTALL CORE
  - if %APPVEYOR_REPO_TAG% equ true if %APPVEYOR_REPO_BRANCH% == master install_core
# BUILD SETUP
  - if %APPVEYOR_REPO_TAG% equ true if %APPVEYOR_REPO_BRANCH% == master build_setup
# BUILD ARTEFACTS
  - if %APPVEYOR_REPO_TAG% equ true if %APPVEYOR_REPO_BRANCH% == master build_artefacts

deploy_script:
# DEPLOY
  - if %APPVEYOR_REPO_TAG% equ true if %APPVEYOR_REPO_BRANCH% == master deploy
