version: 2
jobs:
  build:
    docker:
      - image: babiole/xenial_qt5_9_4:v1
    steps:
      - checkout
      - run:
          name: init_qt_variables
          command: |
            QTDIR="/opt/qt59";
            PATH="$QTDIR/bin:$PATH";
      - run:
          name: compile
          command: |
            chmod +x ./scripts/build.sh
            ./scripts/build.sh


workflows:
  version: 2
  build_and_test:
    jobs:
      - build