version: 2
jobs:
  build:
    docker:
      - image: babiole/xenial_qt5_9_4:v1
    steps:
      - checkout
      - run:
          name: compile
          command: sudo ./scripts/build.sh -both

workflows:
  version: 2
  build_and_test:
    jobs:
      - build