version: 2
jobs:
  build:
    docker:
      - image: babiole/xenial_qt5_10:v1
    steps:
      - checkout
      - run:
          name: init_qt_variables
          command: |
            QTDIR="/opt/qt510";
            PATH="$QTDIR/bin:$PATH";
      - run:
          name: init_submodule
          command: |
            git submodule init
            git submodule update
      - run:
          name: compile
          command: |
            export CMAKE_PREFIX_PATH=/opt/qt510/lib/cmake
            chmod +x ./scripts/build.sh
            ./scripts/build.sh


workflows:
  version: 2
  build_and_test:
    jobs:
      - build