version: 2
jobs:
  build:
    docker:
      - image: ubuntu:trusty
    steps:
      - restore_cache:
          keys: qtfolder
      - run:
          command: sudo apt-get update -y; true;
      - run:
          command: sudo apt-get install software-properties-common;
      - run:
          command: sudo apt-get install python3-software-properties;
      - run:
          command: sudo add-apt-repository ppa:beineri/opt-qt594-trusty -y;
      - run:
          command: sudo apt-get update -y; true;
      - run:
          command: sudo apt-get install -y qt59base qt59imageformats qt59svg qt59declarative qt59graphicaleffects qt59quickcontrols2;

      - save_cache:
          key: qtfolder
          paths:
            - /opt/qt59
      - checkout


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
