version: 2
jobs:
  buildLinux:
    docker:
      - image: babiole/xenial_qt5_9_4:v1
    steps:
      - checkout
      - run:
          name: init_qt_variables
          command: |
            QTDIR="/opt/qt59";
            PATH="$QTDIR/bin:$PATH";
      - run:
          name: compile
          command: |
            export CMAKE_PREFIX_PATH=/opt/qt59/lib/cmake
            chmod +x ./scripts/build.sh
            ./scripts/build.sh
  buildMacOS:
    machine:
      xcode:
        version: 9.2.0


workflows:
  version: 2
  build_and_test:
    jobs:
      - buildLinux
      - buildMacOS