version: 2
jobs:
  build:
    docker:
      - image: ubuntu:trusty
    steps:
      - run:
          name: update_ubuntu
          command: |
            sudo apt-get update -y;
            sudo apt-get install -y ca-certificates;
            sudo apt-get install software-properties-common -y;
            sudo apt-get install python3-software-properties -y;
            sudo apt-get update -y;

      - restore_cache:
          keys: 
            - qtfolder
            - g++
      - run:
          name: install_dep
          command: |
            if [ ! -e /opt/qt59/bin ]; then
              sudo add-apt-repository ppa:beineri/opt-qt594-trusty -y;
              sudo apt-get update -y;
              sudo apt-get install -y qt59base qt59imageformats qt59svg qt59declarative qt59graphicaleffects qt59quickcontrols2;
            fi
            if [ ! -e /usr/bin/g++-6 ]; then
              sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test ;
              sudo apt-get update -y;
              sudo apt-get install -qq g++-6;
              sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90;
            fi
      - save_cache:
          key: qtfolder
          paths:
            - /opt/qt59
      - save_cache:
          key: g++
          paths:
            - /usr/bin/g++-6
      - checkout
      - run:
          name: init_qt_variables
          command: |
            QTDIR="/opt/qt59";
            PATH="$QTDIR/bin:$PATH";
            source /opt/qt59/bin/qt59-env.sh;
            export CMAKE_PREFIX_PATH=/opt/qt59/lib/cmake ;
      - run:
          name: compile
          command: |
            ~/Duly-GUI/scripts/build.sh -both


workflows:
  version: 2
  build_and_test:
    jobs:
      - build