version: 2
jobs:
  buildLinux:
    docker:
      - image: debian:trusty

    steps:
	  - run:
	      name: install_dep
          command:
		    - >
			  sudo apt-get install apt -y
			  sudo add-apt-repository ppa:beineri/opt-qt594-trusty -y
			  sudo apt-get update -y; true
			  sudo apt-get install -y qt59base qt59imageformats qt59svg qt59declarative qt59graphicaleffects qt59quickcontrols2

      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date

  builMacOS:
    macos:
      xcode: "9.0"
    steps:
	  - checkout

workflows:
  version: 2
  build_and_test:
    jobs:
      - buildLinux
      - builMacOS
